sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - "$HOME/.npm"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - commitlint-travis
after_success:
  - npm run semantic-release
